
CREATE TABLE PATIENTS
(
	ID_PATIENT INTEGER NOT NULL PRIMARY KEY IDENTITY,
	CPF VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	BIRTH_DATE DATE,
	INICIO DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
	FIM DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
		PERIOD FOR SYSTEM_TIME (INICIO, FIM)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = DBO.PATIENTSHISTORICO))

CREATE TABLE DOCTORS
(
	ID_DOCTOR INTEGER NOT NULL PRIMARY KEY IDENTITY,
	CPF VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	CRM VARCHAR(50) NOT NULL,
	SPECIALTY VARCHAR(50) NOT NULL,
	OFFICE VARCHAR(50) NOT NULL,
	SALARY FLOAT NOT NULL,
	INICIO DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
	FIM DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
		PERIOD FOR SYSTEM_TIME (INICIO, FIM)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = DBO.DOCTORSHISTORICO))

CREATE TABLE EXAMS
(
	ID_EXAM INT PRIMARY KEY NOT NULL IDENTITY,
	TIPO VARCHAR(50),
	DESCRIPTION VARCHAR(50),
)

CREATE TABLE APPOINTMENTS
(
	ID_APPOINTMENT INT PRIMARY KEY NOT NULL IDENTITY,
	ID_PATIENT INT FOREIGN KEY REFERENCES PATIENTS(ID_PATIENT),
	ID_DOCTOR INT FOREIGN KEY REFERENCES DOCTORS(ID_DOCTOR),
	ID_EXAM INT FOREIGN KEY REFERENCES EXAMS(ID_EXAM),
	DATA_APPOINTMENT VARCHAR(20) NOT NULL,
	RESULT VARCHAR(30) NOT NULL,
	INICIO DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
	FIM DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
		PERIOD FOR SYSTEM_TIME (INICIO, FIM)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = DBO.APPOINTMENTSHISTORICO))

--INSERTS PARA INSERIR DADOS NAS TABELAS
INSERT INTO PATIENTS(CPF, NAME, ADDRESS, BIRTH_DATE)
VALUES ('12345678912', 'DIEGO', 'CAMOBI', '1992-05-15');
INSERT INTO PATIENTS(CPF, NAME, ADDRESS, BIRTH_DATE)
VALUES ('14785236987', 'LUAN', 'CENTRO', '1960-03-23');
INSERT INTO PATIENTS(CPF, NAME, ADDRESS, BIRTH_DATE)
VALUES ('98745632145', 'FERREIRA', 'TACREDO NEVES', '1987-02-14');
INSERT INTO PATIENTS(CPF, NAME, ADDRESS, BIRTH_DATE)
VALUES ('99666332587', 'SILVA', 'CENTRO', '1999-08-02');

INSERT INTO DOCTORS(CPF, NAME, ADDRESS, BIRTH_DATE, CRM, SPECIALTY, OFFICE, SALARY)
VALUES('123456789788', 'JULIO', 'CENTRO', '1960-05-15', '111111', 'PNEUMOLOGISTA', 'CARDIOLOGISTA', 8100.00);
INSERT INTO DOCTORS(CPF, NAME, ADDRESS, BIRTH_DATE, CRM, SPECIALTY, OFFICE, SALARY)
VALUES('123456789789', 'SARTURI', 'CAMOBI', '1962-10-10', '111112', 'CLÍNICO GERAL', 'CLÍNICO GERAL', 6800.00);
INSERT INTO DOCTORS(CPF, NAME, ADDRESS, BIRTH_DATE, CRM, SPECIALTY, OFFICE, SALARY)
VALUES('123456789790', 'ALMEIDA', 'CENTRO', '1950-01-21', '111113', 'ORTOPEDISTA', 'ORTOPEDISTA', 8100.00);
INSERT INTO DOCTORS(CPF, NAME, ADDRESS, BIRTH_DATE, CRM, SPECIALTY, OFFICE, SALARY)
VALUES('123456789781', 'JULIA', 'CAMOBI', '2000-01-01', '111114', 'NEUROCIRURGIÃ', 'NEUROCIRURGIÃ', 6800.00);

INSERT INTO EXAMS(TIPO, DESCRIPTION)
VALUES ('EXAM', 'SANGUE')
INSERT INTO EXAMS(TIPO, DESCRIPTION)
VALUES ('EXAM', 'URINA')
INSERT INTO EXAMS(TIPO, DESCRIPTION)
VALUES ('EXAM', 'RAIO-X')
INSERT INTO EXAMS(TIPO, DESCRIPTION)
VALUES ('EXAM', 'RESSONÂNCIA MAGNÉTICA')

INSERT INTO APPOINTMENTS(ID_PATIENT, ID_DOCTOR, ID_EXAM, DATA_APPOINTMENT, RESULT)
VALUES ('2', '1', '1', '2022-09-30 13:00:00', 'SEM ALTERAÇÕES');
INSERT INTO APPOINTMENTS(ID_PATIENT, ID_DOCTOR, ID_EXAM, DATA_APPOINTMENT, RESULT)
VALUES ('1', '2', '4', '2022-09-17 14:00:00', 'GLICOSE ALTERADA');

UPDATE DOCTORS SET NAME = 'JULIO SARTURTI' WHERE ID_DOCTOR = 1
UPDATE PATIENTS SET BIRTH_DATE = '1978-02-14' WHERE ID_PATIENT = 3
UPDATE APPOINTMENTS SET RESULT = 'TA TUDO RUIM' WHERE ID_APPOINTMENT = 1

SELECT * FROM PATIENTS;
SELECT * FROM DOCTORS;
SELECT * FROM EXAMS;
SELECT * FROM APPOINTMENTS;

SELECT * FROM DBO.PATIENTSHISTORICO;
SELECT * FROM DBO.DOCTORSHISTORICO;
SELECT * FROM DBO.APPOINTMENTSHISTORICO;

ALTER TABLE PATIENTS SET (SYSTEM_VERSIONING = OFF)
ALTER TABLE DOCTORS SET (SYSTEM_VERSIONING = OFF)
ALTER TABLE APPOINTMENTS SET (SYSTEM_VERSIONING = OFF)

DROP TABLE APPOINTMENTS;
DROP TABLE DBO.APPOINTMENTSHISTORICO

DROP TABLE DOCTORS;
DROP TABLE DBO.DOCTORSHISTORICO;

DROP TABLE PATIENTS;
DROP TABLE DBO.PATIENTSHISTORICO;

DROP TABLE EXAMS;