--Nome do produto, nome do fornecedor, nome da categoria, preço e estoque
SELECT
	P.PRODUCTNAME,
	S.COMPANYNAME,
	C.CATEGORYNAME,
	P.UNITPRICE,
	P.UNITSINSTOCK
FROM PRODUCTS AS P
JOIN SUPPLIERS AS S ON S.SUPPLIERID = P.SUPPLIERID
JOIN CATEGORIES AS C ON C.CATEGORYID = P.CATEGORYID

--Ocultar produtos com estoque zerado e descontinuados
SELECT
	P.PRODUCTNAME,
	S.COMPANYNAME,
	C.CATEGORYNAME,
	P.UNITPRICE,
	P.UNITSINSTOCK
FROM PRODUCTS AS P
JOIN SUPPLIERS AS S ON S.SUPPLIERID = P.SUPPLIERID
JOIN CATEGORIES AS C ON C.CATEGORYID = P.CATEGORYID
WHERE P.UNITSINSTOCK > 0 OR P.DISCONTINUED = 0

--Listar produtos com estoque zerado ou descontinuados
SELECT
	P.PRODUCTNAME,
	P.UNITSINSTOCK,
	P.DISCONTINUED
FROM PRODUCTS AS P
WHERE P.UNITSINSTOCK = 0 OR P.DISCONTINUED = 1

--Nome do vendedor e a quantidade de vendas que ele possui
SELECT
	E.FIRSTNAME,
	COUNT(O.ORDERID) AS ORDERS
FROM EMPLOYEES AS E
JOIN ORDERS AS O ON O.EMPLOYEEID = E.EMPLOYEEID
GROUP BY E.FIRSTNAME

--Nome do vendedor e quantidade de territórios aos quais ele está vinculado
SELECT
	E.FIRSTNAME,
	COUNT(ET.TERRITORYID) AS TERRITORIES
FROM EMPLOYEETERRITORIES AS ET
JOIN EMPLOYEES AS E ON E.EMPLOYEEID = ET.EMPLOYEEID
JOIN TERRITORIES AS T ON T.TERRITORYID = ET.TERRITORYID
GROUP BY E.FIRSTNAME

--Vendas ordernadas por valor total, do maior ao menor
SELECT
	O.ORDERID,
	(OD.QUANTITY * OD.UNITPRICE) AS PRICE
FROM ORDERS AS O
JOIN [ORDER DETAILS] AS OD ON OD.ORDERID = O.ORDERID
ORDER BY PRICE DESC

--Vendas em que o produto foi vendido mais barato do que o valor de compra
SELECT
	O.ORDERID,
	P.UNITPRICE AS 'Bought for',
	OD.UNITPRICE AS 'Sold for'
FROM [ORDER DETAILS] AS OD
JOIN ORDERS AS O ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS AS P ON P.PRODUCTID = OD.PRODUCTID
WHERE OD.UNITPRICE < P.UNITPRICE