CREATE DATABASE ativ1EduPalharini;
USE ativ1EduPalharini;

CREATE TABLE PESSOA(
      idPessoa integer not null identity,
      nome varchar(50),
      ano integer,
      maioridade char(3)
)

INSERT INTO PESSOA(nome, ano)
VALUES('AMANDA', 2010);


INSERT INTO PESSOA(nome, ano)
VALUES('JORGE', 1995);

SELECT * FROM PESSOA;

CREATE TRIGGER VERIFICARMAIORIDADE
ON PESSOA
AFTER INSERT
AS
      DECLARE @IDADE INTEGER
      SELECT @IDADE = (SELECT SUM(2022-ANO) FROM INSERTED)
      IF @IDADE >=18
            BEGIN
            UPDATE PESSOA SET MAIORIDADE = 'SIM'
                  WHERE PESSOA.IDPESSOA = (SELECT INSERTED.IDPESSOA FROM INSERTED         
                  JOIN PESSOA ON INSERTED.IDPESSOA = PESSOA.IDPESSOA)
            END
      ELSE
            BEGIN
            UPDATE PESSOA SET MAIORIDADE = 'NAO'
                  WHERE PESSOA.IDPESSOA = (SELECT INSERTED.IDPESSOA FROM INSERTED         
                  JOIN PESSOA ON INSERTED.IDPESSOA = PESSOA.IDPESSOA)
            END


DROP TRIGGER VERIFICARMAIORIDADE