


-- LISTAR AS VENDAS ORDENANDO PELO VALOR MAIOR PARA MENOR
SELECT ORDERS.ORDERID,
	([ORDER DETAILS].QUANTITY * [ORDER DETAILS].UNITPRICE) AS TOTAL
FROM ORDERS
JOIN [ORDER DETAILS] ON [ORDER DETAILS].ORDERID = ORDERS.ORDERID
ORDER BY ([ORDER DETAILS].QUANTITY * [ORDER DETAILS].UNITPRICE) DESC



-- LISTAR AS VENDAS ONDE O PRODUTO FOI VENDIDO MAIS BARATO QUE PELO PREÇO DE CUSTO
SELECT DISTINCT [ORDER DETAILS].ORDERID, PRODUCTS.UNITPRICE, [ORDER DETAILS].UNITPRICE
FROM [ORDER DETAILS]
JOIN PRODUCTS ON [ORDER DETAILS].PRODUCTID = PRODUCTS.PRODUCTID
AND [ORDER DETAILS].UNITPRICE < PRODUCTS.UNITPRICE
