CREATE DATABASE Atividade

USE Atividade

CREATE TABLE Paciente
(
	idPaciente INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(50) NOT NULL, 
	cpf VARCHAR(15) NOT NULL, 
	endereco  VARCHAR(30) NOT NULL,
	dataNasc DATE NOT NULL,
	inicio DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL, 
	fim DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME(inicio,fim)
)

CREATE TABLE Medico
(
	idMedico INTEGER NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(50) NOT NULL, 
	cpf VARCHAR(15) NOT NULL, 
	endereco  VARCHAR(30) NOT NULL,
	dataNasc DATE NOT NULL,
	crm VARCHAR(10) NOT NULL, 
	especialidade VARCHAR(20) NOT NULL, 
	cargo VARCHAR(30) NOT NULL, 
	salario FLOAT NOT NULL,
	inicio DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL, 
	fim DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME(inicio,fim)
)

CREATE TABLE Exame
(
	idExame INTEGER NOT NULL PRIMARY KEY IDENTITY,
	info VARCHAR(100) NOT NULL,
)

CREATE TABLE Consulta
(
	idPaciente INTEGER NOT NULL, 
	idMedico INTEGER NOT NULL, 
	idExame INTEGER NOT NULL, 
	resultadoExames VARCHAR(100) NOT NULL,
	inicio DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL, 
	fim DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME(inicio,fim),

	FOREIGN KEY (idPaciente) REFERENCES Paciente(idPaciente),
	FOREIGN KEY (idMedico) REFERENCES Medico(idMedico),
	FOREIGN KEY (idExame) REFERENCES Exame(idExame),
	PRIMARY KEY(idPaciente,idMedico,idExame)
)